import type { Metadata } from "next";
import {Inter, Poppins} from "next/font/google";
import "./globals.css";
import React from "react";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-heading",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable} antialiased min-h-full flex flex-col`}>
      <main>{children}</main>
      </body>
    </html>
  );
}
